pragma Singleton
import QtQuick

QtObject {
    readonly property color md_theme_light_primary: "#6750A4"
    readonly property color md_theme_light_onPrimary: "#FFFFFF"
    readonly property color md_theme_light_primaryContainer: "#EADDFF"
    readonly property color md_theme_light_onPrimaryContainer: "#21005E"
    readonly property color md_theme_light_secondary: "#625B71"
    readonly property color md_theme_light_onSecondary: "#FFFFFF"
    readonly property color md_theme_light_secondaryContainer: "#E8DEF8"
    readonly property color md_theme_light_onSecondaryContainer: "#1E192B"
    readonly property color md_theme_light_tertiary: "#7D5260"
    readonly property color md_theme_light_onTertiary: "#FFFFFF"
    readonly property color md_theme_light_tertiaryContainer: "#FFD8E4"
    readonly property color md_theme_light_onTertiaryContainer: "#370B1E"
    readonly property color md_theme_light_error: "#B3261E"
    readonly property color md_theme_light_onError: "#FFFFFF"
    readonly property color md_theme_light_errorContainer: "#F9DEDC"
    readonly property color md_theme_light_onErrorContainer: "#410E0B"
    readonly property color md_theme_light_background: "#FFFBFE"
    readonly property color md_theme_light_onBackground: "#1C1B1F"
    readonly property color md_theme_light_surface: "#FFFBFE"
    readonly property color md_theme_light_onSurface: "#1C1B1F"
    readonly property color md_theme_light_surfaceVariant: "#E7E0EC"
    readonly property color md_theme_light_onSurfaceVariant: "#49454F"
    readonly property color md_theme_light_outline: "#79747E"
    readonly property color md_theme_light_outlineVariant: "#CAC4D0"
    readonly property color md_theme_light_surfaceContainerLowest: "#FFFFFF"
    readonly property color md_theme_light_surfaceContainerLow: "#F7F2FA"
    readonly property color md_theme_light_surfaceContainer: "#F3EDF7"
    readonly property color md_theme_light_surfaceContainerHigh: "#ECE6F0"
    readonly property color md_theme_light_surfaceContainerHighest: "#E6E0E9"

    readonly property color md_theme_dark_primary: "#D0BCFF"
    readonly property color md_theme_dark_onPrimary: "#381E72"
    readonly property color md_theme_dark_primaryContainer: "#4F378A"
    readonly property color md_theme_dark_onPrimaryContainer: "#EADDFF"
    readonly property color md_theme_dark_secondary: "#CCC2DC"
    readonly property color md_theme_dark_onSecondary: "#332D41"
    readonly property color md_theme_dark_secondaryContainer: "#4A4458"
    readonly property color md_theme_dark_onSecondaryContainer: "#E8DEF8"
    readonly property color md_theme_dark_tertiary: "#EFB8C8"
    readonly property color md_theme_dark_onTertiary: "#492533"
    readonly property color md_theme_dark_tertiaryContainer: "#633B48"
    readonly property color md_theme_dark_onTertiaryContainer: "#FFD8E4"
    readonly property color md_theme_dark_error: "#F2B8B5"
    readonly property color md_theme_dark_onError: "#601410"
    readonly property color md_theme_dark_errorContainer: "#8C1D18"
    readonly property color md_theme_dark_onErrorContainer: "#F9DEDC"
    readonly property color md_theme_dark_background: "#1C1B1F"
    readonly property color md_theme_dark_onBackground: "#E6E1E5"
    readonly property color md_theme_dark_surface: "#1C1B1F"
    readonly property color md_theme_dark_onSurface: "#E6E1E5"
    readonly property color md_theme_dark_surfaceVariant: "#49454F"
    readonly property color md_theme_dark_onSurfaceVariant: "#CAC4D0"
    readonly property color md_theme_dark_outline: "#938F99"
    readonly property color md_theme_dark_outlineVariant: "#49454F"
    readonly property color md_theme_dark_surfaceContainerLowest: "#0F0D13"
    readonly property color md_theme_dark_surfaceContainerLow: "#1D1B20"
    readonly property color md_theme_dark_surfaceContainer: "#211F26"
    readonly property color md_theme_dark_surfaceContainerHigh: "#2B2930"
    readonly property color md_theme_dark_surfaceContainerHighest: "#36343B"
}
